#!/usr/bin/env bash
# Installs Nginx with the following configurations
sudo apt-get update -y
sudo apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo echo "Holberton School" > /etc/nginx/html/index.nginx-debian.html
sudo service nginx restart
