#!/usr/bin/env bash
# Installs Nginx with the following configurations
sudo apt-get update -y
sudo apt-get install -y nginx
sudo echo "Holberton School" > /etc/nginx/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'

sudo service nginx restart
