#!/usr/bin/env bash
# Script that install and configure HAproxy on server.
sudo apt -y install haproxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http_web
    bind *:80
    default_backend rgw
backend rgw
    balance roundrobin
    server  rgw1 34.148.160.36:80 check
    server  rgw2 184.72.175.91:80 check
EOT
sudo service haproxy start
