#!/usr/bin/env bash
#display fizzBuzz or Fizz or Buzz or x
for ((x=1;x<101;x++))
do
if (( (( x % 3 == 0 )) && (( x % 5 == 0 )) ))
then
    echo "FizzBuzz"
elif ((x % 3 == 0))
then
    echo "Fizz"
elif ((x % 5 == 0))
then
    echo "Buzz"
else
    echo "$x"
fi
done
